### ISSUE TITLE
Erroring out

### ISSUE THREAD

**Issue by Goten87** [Naliwe/bitBurner-scripts#1]
when i try to download/run this it will give me a error sins it cannot find /lib/Constants.ns in the pullFiles.ns file
so i think the lib system is not working correct

i think the import of lib files is not correct

Error Code
```RUNTIME ERROR
/bin/utils/pullFiles.ns@home

Failed to resolve module specifier "/lib/Constants.ns". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/lib/Constants.ns". Invalid relative url or base scheme isn't hierarchical.```

**Comment by Naliwe** [comment]
Hello :)
You should first use the `initRepo.ns` script as mentioned in the Readme.
Check my template repo for more info, this is repo is my personal game files (which you're free to use of course):
https://github.com/Naliwe/bitBurnerTsProject

**Comment by Naliwe** [comment]
For reference:
![image](https://user-images.githubusercontent.com/7049553/147419555-10d93f59-56a4-436d-914d-17eabcd66980.png)

**Comment by Goten87** [comment]
i get it when i run the `run /bin/utils/initRepo.ns` code
sorry made a misstake in the first post

i run it then when it gets to `Running download script` it crashes with the error code
```
RUNTIME ERROR
/bin/utils/pullFiles.ns@home

Failed to resolve module specifier "/lib/Constants.ns". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/lib/Constants.ns". Invalid relative url or base scheme isn't hierarchical.
```

im trying to use it in a browser but i think that shout not matter at all sins its the same version as the steam client one

**Comment by Naliwe** [comment]
Hmm, that's strange:

https://github.com/Naliwe/bitBurner-scripts/blob/d0c2bd5f718296ca17c901811cc8bbbe32f69234/src/bin/utils/initRepo.ts#L1

That's the only import in `initRepo.ns` so it should not even try to look for `Constants.ns`. Can you check if the `/lib/Constants.ns` exists in your game filesystem ? I don't play on the browser version so maybe there is a difference (I would be suprised though, as you said, it should be the same version on Steam).

**Comment by Naliwe** [comment]
Ah, yeah, sorry, I know what I did x) I changed `Helpers.ts` on this repo but not on the template repo :p So yeah, just `wget http://localhost:9182/lib/Constants.ns /lib/Constants.ns` or add it to the `initRepo.ns` `params` constant.

Or start from the template repo instead of this one, this one is just my files so I don't particularily pay attention to its usability by others :P The template should be fine though, it's just the skeleton with minimal `imports` specifically to avoid these sorts of problems :P

**Comment by Naliwe** [comment]
I just fixed the initialization: https://github.com/Naliwe/bitBurner-scripts/commit/3c2ab56cdb883e0752b60e4787142be7d54ed093 if you wanna try :)

But again, I'd recommend starting from the template repo to play around with it. You can of course just switch to this repo once you get the hang of it afterwards.

**Comment by Goten87** [comment]
still happens

**Comment by Goten87** [comment]
i use chrome 96.0.4664.110 (Officiële build) (64-bits) to use it on browser on my vm to test sins my main game i code my self xD just wanted to see what your system is about

also i heard that the .ns files are depricated so you need to change your system a little to use .js files

**Comment by Naliwe** [comment]
Huh? I haven't seen that on steam, and they are the same, it's just an extension :p I use `ns` just because it makes sense for NetScript :) And because there is technically a transformation phase (the `import` statements are limited in the game) so it's not really `js`

And yeah I just noticed I forgot to add the new file to the list, I couldn't test since I did the change on my phone :p

**Comment by Naliwe** [comment]
Should be fine now: https://github.com/Naliwe/bitBurner-scripts/commit/8008c770dd353d8ed1d745d18e06498e35622902

**Comment by Goten87** [comment]
yep it works now xD

**Comment by Naliwe** [comment]
Great! Closing the issue :)
